Repository wecode-bootcamp-korea/37-2nd-yourhouse-backend, pull requests merged in 2022-10, with the labels that each got.

#1 백엔드 초기 세팅
  .env.sample
  .gitignore
  app.js
  controllers/index.js
  controllers/pingController.js
  middleware/errorHandler.js
  models/dataSource.js
  package-lock.json
  package.json
  routes/index.js
  routes/pingRouter.js
  services/index.js
  services/pingService.js
  util/error.js
Labels: 완료

#4 [ADD]카카오 소셜 로그인/회원가입 구현, 유닛 테스트
  .env.sample
  .gitignore
  app.js
  controllers/index.js
  controllers/userController.js
  middleware/auth.js
  models/index.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/userRouter.js
  server.js
  services/index.js
  services/userService.js
  tests/user.test.js
  util/error.js
  util/socialAuth.js
Labels: 완료

#8 [ADD] 유저, 포스트 정보, nav 자동완성, 검색 결과 표시
  controllers/index.js
  controllers/searchController.js
  middleware/auth.js
  models/index.js
  models/searchDao.js
  routes/index.js
  routes/searchRouter.js
  services/index.js
  services/searchService.js
Labels: 멘토 리뷰 요청

#7 정렬 필터링 완료
  controllers/index.js
  controllers/postController.js
  middleware/auth.js
  models/index.js
  models/postDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/postRouter.js
  routes/profileRouter.js
  routes/searchRouter.js
  services/index.js
  services/postService.js
Labels: 멘토 리뷰 요청

#6 [ADD] 포스팅 댓글 기능
  controllers/commentController.js
  controllers/index.js
  models/commentDao.js
  models/index.js
  models/userDao.js
  package-lock.json
  package.json
  routes/commentRouter.js
  routes/index.js
  services/commentService.js
  services/index.js
  tests/comment.test.js
Labels: 멘토 리뷰 요청

#11 Feature/likes
  controllers/index.js
  controllers/likeController.js
  models/index.js
  models/likeDao.js
  routes/likeRouter.js
  routes/profileRouter.js
  services/index.js
  services/likeService.js
Labels: 멘토 리뷰 요청

#13 댓글 삭제 수정
  controllers/commentController.js
  models/commentDao.js
  models/postDao.js
  routes/commentRouter.js
  services/commentService.js
Labels: 멘토 리뷰 요청

#10 [ADD] posting data 및 image
  .env.test
  app.js
  controllers/index.js
  controllers/postingController.js
  models/dataSource.js
  models/index.js
  models/postDao.js
  models/postingDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/postingRouter.js
  services/index.js
  services/postingService.js
  util/multer.js
Labels: 멘토 리뷰 요청

#9 [ADD] 포스트 디테일 페이지
  app.js
  controllers/commentController.js
  controllers/index.js
  controllers/postController.js
  controllers/userController.js
  models/commentDao.js
  models/dataSource.js
  models/database.js
  models/index.js
  models/likeDao.js
  models/postDao.js
  models/postingDao.js
  models/profileDao.js
  models/searchDao.js
  models/userDao.js
  routes/commentRouter.js
  routes/index.js
  routes/likeRouter.js
  routes/postRouter.js
  routes/postingRouter.js
  services/index.js
  services/postService.js
  services/userService.js
  tests/Profile.test.js
  tests/user.test.js
  util/multer.js
  util/socialAuth.js
Labels: 수정 요청
